server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.aihwaong.minicm.mapper: debug
spring:
  datasource:
    name: aihwaong_minicm
    url: jdbc:mysql://127.0.0.1:3306/aihwaong_minicm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host:
    port: